spring:
  application:
    name: demo
  datasource:
    url: jdbc:h2:mem:testdb
    username: root
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: 'create'